name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test PHP App
    runs-on: debian-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: project
          MYSQL_USER: user
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_mysql, mbstring, exif, pcntl, bcmath, gd
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHP Syntax Check
        run: find . -type f -name "*.php" -exec php -l {} \;

      - name: Run PHP Unit Tests (if any)
        run: vendor/bin/phpunit --testdox || echo "No tests found"

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: debian-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/community-forum
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            systemctl restart apache2
